using System;
using System.Collections.Generic;
using System.Text;

namespace gb.mbs.da.model.patient.note
{
    public class PTNote : Note
    {
       public string DoctorSign { set; get; }
       public string PatientSign { set; get; }
       public string EventId { set; get; }
       public string PrecAutions{ set; get; }
       public string DtDate { set; get; }
       public string Complaints { set; get; }
       public string Objective1 { set; get; }
       public string Objective2 { set; get; }
       public string Objective3 { set; get; }
       public string PatientTolerated { set; get; }
       public string AssotherComments { set; get; }
       public string OtherComments { set; get; }
       public string CotinueTherapy { set; get; }
       public string PlanOtherComments { set; get; }
       public string PlanOherComments2 { set; get; }
       public string Mild { set; get; }
       public string Moderate { set; get; }
       public string Severe { set; get; }
       public string Verysevere { set; get; }
       public string Headacheright { set; get; }
       public string Headacheleft { set; get; }
       public string Headacheboth { set; get; }
       public string Neckright { set; get; }
       public string Neckleft { set; get; }
       public string Neckboth { set; get; }
       public string Midbackright { set; get; }
       public string Midbackleft { set; get; }
       public string Midbackboth { set; get; }
       public string Lowbackright { set; get; }
       public string Lowbackleft { set; get; }
       public string Lowbackboth { set; get; }
       public string Jawright { set; get; }
       public string Jawleft { set; get; }
       public string Jawboth { set; get; }
       public string ShoulderRight { set; get; }
       public string ShoulderLeft { set; get; }
       public string ShoulderBoth { set; get; }
       public string ElbowRight { set; get; }
       public string ElbowLeft { set; get; }
       public string Elbowboth { set; get; }
       public string WristRight { set; get; }
       public string WristLeft { set; get; }
       public string WristBoth { set; get; }
       public string HandRight { set; get; }
       public string HandLeft { set; get; }
       public string HandBoth { set; get; }
       public string FingersRight { set; get; }
       public string FingersLeft { set; get; }
       public string FingersBoth { set; get; }
       public string HipRight { set; get; }
       public string HipLeft { set; get; }
       public string HipBoth { set; get; }
       public string ThighRight { set; get; }
       public string ThighLeft { set; get; }
       public string ThighBoth { set; get; }
       public string KneeRight { set; get; }
       public string KneeLeft { set; get; }
       public string KneeBoth { set; get; }
       public string LowerlegRight { set; get; }
       public string LowerlegLeft { set; get; }
       public string LowerlegBoth { set; get; }
       public string FootRight { set; get; }
       public string FootLeft { set; get; }
       public string FootBoth { set; get; }
       public string ToesRight { set; get; }
       public string ToesLeft { set; get; }
       public string ToesBoth { set; get; } 
       public string PatientSignPath { set; get; }
       public string DoctorSignPath { set; get; }
       public string BarCodePath { set; get; }
       public string TreatmentHeadacheRight { set; get; }
       public string TreatmentHeadacheLeft { set; get; }
       public string TreatmentHeadacheboth { set; get; }
       public string TreatmentNeckRight { set; get; }
       public string TreatmentNeckLeft { set; get; } 
       public string TreatmentNeckBoth { set; get; }
       public string TreatmentMidbackRight { set; get; }
       public string TreatmentMidbackLeft { set; get; } 
       public string TreatmentMidbackBoth { set; get; }
       public string TreatmentLowbackRight { set; get; }
       public string TreatmentLowbackLeft { set; get; }
       public string TreatmentLowbackBoth { set; get; }
       public string TreatmentJawRight { set; get; }
       public string TreatmentJawLeft { set; get; }
       public string TreatmentJawBoth { set; get; }
       public string TreatmentShoulderRight { set; get; }
       public string TreatmentShoulderLeft { set; get; }
       public string TreatmentShoulderboth { set; get; }
       public string TreatmentElbowRight { set; get; }
       public string TreatmentElbowLeft { set; get; }
       public string TreatmentElbowBoth { set; get; }
       public string TreatmentWristRight { set; get; }
       public string TreatmentWristLeft { set; get; }
       public string TreatmentWristBoth { set; get; }
       public string TreatmentHandRight { set; get; }
       public string TreatmentHandLeft { set; get; }
       public string TreatmentHandBoth { set; get; }
       public string TreatmentFingersRight { set; get; }
       public string TreatmentFingersLeft { set; get; }
       public string TreatmentFingersboth { set; get; }
       public string TreatmentHipRight { set; get; }
       public string TreatmentHipLeft { set; get; }
       public string TreatmentHipBoth { set; get; }
       public string TreatmenttHighRight { set; get; } 
       public string TreatmenttHighLeft { set; get; }
       public string TreatmenttHighBoth { set; get; }
       public string TreatmentKneeRight { set; get; }
       public string TreatmentkneeLeft { set; get; }
       public string TreatmentKneeBoth { set; get; }
       public string TreatmentLowerLegRight { set; get; }
       public string TreatmentLowerLegLeft { set; get; }
       public string TreatmentLowerLegboth { set; get; }
       public string TreatmentFootRight { set; get; }
       public string TreatmentFootLeft { set; get; }
       public string TreatmentFootBoth { set; get; }
       public string TreatmentToesRight { set; get; }
       public string TreatmentToesLeft { set; get; }
       public string TreatmentToesBoth { set; get; }
       public string PainlevelHeadache { set; get; }
       public string PainlevelNeck { set; get; }
       public string PainlevelMidback { set; get; } 
       public string PainlevelLowback  { set; get; }
       public string PainlevelJaw { set; get; }
       public string PainlevelShoulder { set; get; }
       public string PainlevelElbow { set; get; }
       public string PainlevelWrist { set; get; }
       public string PainlevelHand { set; get; }
       public string PainlevelFingers { set; get; }
       public string PainlevelHip { set; get; }
       public string PainlevelThigh { set; get; }
       public string PainlevelKnee { set; get; }
       public string PainlevelLowerleg { set; get; }
       public string PainlevelFoot { set; get; }
       public string PainlevelToes { set; get; }
       public string ArmRight { set; get; }
       public string ArmLeft { set; get; }
       public string ArmBoth { set; get; }
       public string AnkleRight { set; get; }
       public string AnkleLeft { set; get; }
       public string AnkleBoth { set; get; }
       public string ForeArmRight { set; get; }
       public string ForeArmLeft { set; get; }
       public string ForeArmBoth { set; get; }
       public string PainLevelArm { set; get; }
       public string PainLevelAnkle { set; get; }
       public string PainLevelForeArm { set; get; }
       public string TreatmentArmRight { set; get; }
       public string TreatmentArmLeft { set; get; }
       public string TreatmentArmBoth { set; get; }
       public string TreatmentForeArmRight { set; get; }
       public string TreatmentForeArmLeft { set; get; }
       public string TreatmentForeArmBoth { set; get; }
       public string TreatmentAnkleRight { set; get; }
       public string TreatmentAnkleLeft { set; get; }
       public string TreatmentAnkleBoth { set; get; }
       public string DoctorName { set; get; }
    }  
}      
       